FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /source
COPY . .
RUN dotnet restore
WORKDIR /source/CharlieBackend.Api
RUN dotnet build ./CharlieBackend.Api.csproj --configuration Release
RUN dotnet publish -c release -o /app --no-restore
RUN touch /app/.env

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:3.1.22-alpine3.14
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "CharlieBackend.Api.dll"]
